name: movie_pipeline_airflow

services:
  db:
    container_name: postgredb
    image: postgres:15.10-alpine3.21
    volumes:
      - type: volume
        source: postgres_vol
        target: /var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=admin"

  webserver:
    container_name: airflow_webserver
    image: jayesh0809/airflow_custom:1.1
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/src/airflow/dags
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/src/airflow/logs
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:admin@db:5432/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    env_file:
      - secrets.env
    depends_on:
      - db
    command: webserver

  scheduler:
    container_name: airflow_scheduler
    image: jayesh0809/airflow_custom:1.1
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/src/airflow/dags
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/src/airflow/logs
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:admin@db:5432/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    env_file:
      - secrets.env
    depends_on:
      - webserver
    command: scheduler
    
volumes:
  postgres_vol:


